### ISSUE TITLE
TypeError: (0 , _reactRouterDom.withRouter) is not a function

### ISSUE THREAD

**Issue by achingachris** [achingachris/react-bootstrap-starter#59]
Getting

```
TypeError: (0 , _reactRouterDom.withRouter) is not a function
```

After Updating React Router to version 6.

I'm not sure what I did is the right thing when migrated to v6, but the LinkContainer may have some updates I'm not aware of.

Kindly Assist. (On branch: dev)
![error](https://user-images.githubusercontent.com/50122165/144872251-08439773-340b-4505-b79d-e30b06d0174b.png)
#

Best Regards # #60
